#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker0"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "b7598f4d601b4c4da6cb0d5552d0d6c8" }
]

[assets]
directory = "./public"
